### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by raganmd**
Re-org to focus on better standard approach

### CODE REVIEW

**Comment by cicintrip** [comment]
Hi Matthew! I'm a GitHub starter, so I don't know if its the right place to ask it.
Have you solved the problem of uploading the SVG files? 
I tried to follow your XML tutorial, but I'm still in trouble!

**Comment by raganmd** [comment]
@cicintrip can you say a little bit more about the issue you're having? What exactly do you mean about uploading SVG files?

**Comment by cicintrip** [comment]
I’d like to draw something on illustrator. Then exporting the vector on TD and make it move following for instance the music or something like that. 
I saw the SVG XML article on your blog, but I wasn’t able to solve the issue!

**Comment by raganmd** [comment]
@cicintrip - ahhh. I get it. This TOX is used for making SVGs out of SOPs. You might look here for converting something from illustrator to some geometry:
https://www.youtube.com/watch?v=VZDR8nCYdvU

**Pull request merged**
